### PR TITLE
throw error rather than panic on bad input for padded decoding

### LINKED ISSUE #2: Unexpected/unhandled error when decoding.
Hello, I was using this library to check if a number was in base32 using the decode function. 
```rust
fn is_base32_number(s: &str) -> bool {
    match RFC4648.decode(s.as_bytes()) {
        Ok(_) => true,
        Err(_) => false,
    }
}
```

When I pass a string that has a length less than 6 to the function, it panics with a "attempt to subtract with overflow" without throwing a DecodeError, which is caused by the following function: https://github.com/rogusdev/fast32/blob/e9d804855ec8659e056c0e760ba88d8b5c65f6ea/src/base32/alphabet.rs#L154, more specifically where it tries to index `a[len - 6]`.

I made what i feel like is a bandaid fix, but I have only been writing rust for like a week or 2 so I am not sure if it follows the best conventions and guidelines. 

I am sure this is not an intended function of decode method, but from what I have been reading it would follow Rust conventions to make it as safe as possible.

### PR DESCRIPTION
**Pull request by rogusdev**
Resolves #2

### CODE REVIEW

File: tests/base32.rs [hunk 1]
```diff
@@ -440,38 +440,38 @@ fn both_u64_low() {
...
-    assert_eq!(
-        res.unwrap_err(),
-        DecodeError::InvalidChar {
-            char: '1',
-            index: 1
-        }
-    );
+    assert_eq!(res.unwrap_err(), DecodeError::InvalidChar { char: '1', index: 1 });
+
+    // padding incomplete/missing for decoding
```
Comment (rogusdev) [inline tests/base32.rs:464]: new tests here

File: tests/base64.rs [hunk 2]
```diff
@@ -381,38 +381,38 @@ fn both_u64_low() {
...
-    assert_eq!(
-        res.unwrap_err(),
-        DecodeError::InvalidChar {
-            char: '1',
-            index: 1
-        }
-    );
+    assert_eq!(res.unwrap_err(), DecodeError::InvalidChar { char: '1', index: 1 });
+
+    // padding incomplete/missing for decoding
```
Comment (rogusdev) [inline tests/base64.rs:405]: new tests here

File: src/base32/alphabet.rs [hunk 3]
```diff
@@ -215,20 +214,32 @@ impl Alphabet32Padded {
     /// Pass decoder array to [`decode`](super::decode()), and remove padding as needed
     #[inline]
     pub fn decode(&self, a: &[u8]) -> Result<Vec<u8>, DecodeError> {
-        decode(self.dec, rem_pad(a, self.pad))
+        if a.len() % WIDTH_ENC != 0 {
```
Comment (rogusdev) [inline src/base32/alphabet.rs:217]: New check: make sure this is a valid padded length (still does not verify that it is actually a padded string! -- that will fail for invalid char, or actually parse if it is valid)

File: src/base32/alphabet.rs [hunk 4]
```diff
@@ -70,7 +70,6 @@ make_base32_alpha!(
     b"110abcdefgh1jk1mn0pqrstvwxyz"
 );
 
-
```
Comment (rogusdev) [inline src/base32/alphabet.rs:73]: The small formatting changes in here are from leftover cargo fmt stuff I did not catch in the past (yes, this needs CI)
